### ISSUE TITLE
No instruction set for use in Docker container

### ISSUE THREAD

**Issue by dnade** [hihouhou/huginn_twitter_publishv2_agent#2]
I am unable to use the former v1.1 authentication with "HUGINN_TWITTER_OAUTH_KEY" or the accompanying key secret.  I turned to this to try to use the v2 auth, but I am unsure how to pass these to the docker image I've spun up.

**Comment by hihouhou** [comment]
in .env you can follow [official_doc](https://github.com/huginn/huginn/blob/master/.env.example#L186) and add huginn_twitter_publishv2_agent(github: hihouhou/huginn_twitter_publishv2_agent
for credentials , you need to put them when you will create the agent

**Comment by hihouhou** [comment]
no feed back since 5 days, so closed

**Comment by ZacharyRen77** [comment]
> 在.env中，您可以按照[official_doc](https://github.com/huginn/huginn/blob/master/.env.example#L186)并添加huginn_twitter_publishv2_agent（github：hihouhou/huginn_twitter_publishv2_agent 作为凭据，您需要在创建代理时放置它们

is creating huginn
 Do you use the -e HUGINN_ADDITIONAL_GEMS=huginn_twitter_publishv2_agent(github:hihouhou/huginn_twitter_publishv2_agent) parameter when using a docker container?

**Comment by hihouhou** [comment]
I use .env file with my container but now you can use HUGINN_ADDITIONAL_GEMS=huginn_twitter_publishv2_agent because there is a gem
